export const cities: string[] = [
  'Dallas, TX',
  'Fort Worth, TX',
  'Austin, TX',
  'Houston, TX',
  'San Antonio, TX',
  'New York, NY',
  'Manhattan, NY',
  'Brooklyn, NY',
  'Queens, NY',
  'Chicago, IL',
  'Boston, MA',
  'Atlanta, GA',
  'Nashville, TN',
  'Denver, CO',
  'Boulder, CO',
  'San Francisco, CA',
  'Los Angeles, CA',
  'San Diego, CA',
  'Raleigh, NC',
  'Charlotte, NC',
  'Seattle, WA',
  'Washington DC',
  'Las Vegas, NV',
  'Philadelphia, PA',
  'Phoenix, AZ',
  'New Orleans, LA',
  'Orlando, FL',
  'Charleston, SC',
  'St. Louis, MO',
  'Salt Lake City, UT',
  'Pittsburgh, PA',
  'Portland, OR',
  'Jersey City, NJ',
  'Oakland, CA',
];

export const neighborhoodMap: { [key: string]: string[] } = {
  'Dallas, TX': [
    'Dallas',
    'Fort Worth',
    'Addison',
    'Arlington',
    'Benbrook',
    'Carrollton',
    'Cedar Hill',
    'Coppell',
    'DeSoto',
    'Euless',
    'Farmer’s Branch',
    'Garland',
    'Grand Prairie',
    'Grapevine',
    'Highland Park',
    'Hurst',
    'Irving',
    'Keller',
    'Kennedale',
    'Lewisville',
    'McKinney',
    'Mesquite',
    'Plano',
    'Richardson',
    'University Park',
    'Uptown',
    'Victory Park',
  ],
  'Houston, TX': [
    'Bellaire',
    'Downtown',
    'East End',
    'Galleria',
    'Greenway Plaza',
    'Historic Third Ward',
    'Katy',
    'Kirby',
    'Memorial',
    'Meyerland',
    'Midtown',
    'Montrose',
    'Museum District/Medical',
    'Pasadena',
    'Rice',
    'Rice Military',
    'River Oaks',
    'Sugar Land',
    'Tanglewood',
    'The Heights',
    'The Woodlands',
    'Timber Grove',
    'Uptown',
    'West End',
    'West University',
  ],
};
